### ISSUE TITLE
Add `add/get_alternate_id` to po contract's state module

### ISSUE THREAD

**Issue by shannynalayna** [hyperledger/grid#1010]
Add the `add_alternate_id` & `get_alternate_id` method to the PurchaseOrderState object, within the po smart contract's state module. This will allow for alternate IDs to be added and referenced if passed in to the po smart contract.

**Comment by dnewh** [comment]
After discussion with @shannynalayna, we don't think this is necessary as Alternate IDs are part of the Purchase Order state representation already. Any lookup using alternate IDs is done at the store level.
