### ISSUE TITLE
Create stories for implementing DLT monitoring polling functionality

### ISSUE THREAD

**Issue by shannynalayna** [hyperledger/grid#1291]
Generate stories based on the implementation needs for the DLT monitoring polling functionality

**Comment by leebradley** [comment]
Created:

- https://github.com/hyperledger/grid/issues/1365
- https://github.com/hyperledger/grid/issues/1366
- https://github.com/hyperledger/grid/issues/1367
- https://github.com/hyperledger/grid/issues/1368
