### ISSUE TITLE
Update CLI migrations for new store pattern

### ISSUE THREAD

**Issue by dplumb94** [hyperledger/grid#314]
The CLI should use the new store module functions for running migrations. The connection pool code should be removed.

**Comment by RyanLassigBanks** [comment]
This seems to be a duplicate considering the CLI migration command currently points to the grid_sdk.
https://github.com/hyperledger/grid/blob/0c39cae9bae33890b894b0fda8853d9891332914/cli/src/actions/database.rs#L19
