### ISSUE TITLE
Document PO Example

### ISSUE THREAD

**Issue by dplumb94** [hyperledger/grid#469]

**Comment by JessieZamzow** [comment]
Task Description
Describe the concepts within scope for the Grid Purchase Order RFC and use examples to illustrate the feature.
Think of it as the guide-level explanation.
There is some explanation here - https://github.com/hyperledger/grid-rfcs/blob/master/0000-template.md

**Comment by JessieZamzow** [comment]
Two business scenarios are documented - one is a general/vanilla scenario and the other is a vendor-managed purchasing example. Leaving this task open for this coming sprint given the technical protobuf/permission write-ups will be written and refined against these scenarios.

**Comment by JessieZamzow** [comment]
Closing this task given the Grid Purchase Order RFC was submitted for public review. Two example use cases are outlined within the RFC submission.
