### ISSUE TITLE
Finish implementing purchase order rest api routes

### ISSUE THREAD

**Issue by RyanLassigBanks** [hyperledger/grid#675]
Implement the following endpoints for purchase order api

GET /purchase-order/{uuid}/versions
GET /purchase-order/{uuid}/versions/{version_id}
GET /purchase-order/{uuid}/versions/{version_id}/revisions
GET /purchase-order/{uuid}/versions/{version_id}/revisions/{revision_number}

**Comment by shannynalayna** [comment]
This story is out-of-date and no longer relevant.
