### ISSUE TITLE
Test StateEvent Timestamp for Splinter 0.5 support

### ISSUE THREAD

**Issue by dplumb94** [hyperledger/grid#786]
StateEvent timestamps were updated, but the new version should be backwards-compatible. We should test to ensure that nothing goes wrong with StateEvent handling with Splinter 0.5

**Comment by shannynalayna** [comment]
This issue has been split into separate tasks around testing Grid with Splinter 0.5, here: https://github.com/hyperledger/grid/issues/731, and here: https://github.com/hyperledger/grid/issues/938
